version: '3.1'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
